apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-spring-boot-docker
  labels:
    app: spring
spec:
  replicas: 3
  selector:
      matchLabels:
        app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-boot 
        image: kairemor/spring-boot:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  selector:
    app: spring
  type: LoadBalancer


